//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventChannel()
        {
            this.LightZones = new HashSet<LightZone>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ChannelNo { get; set; }
        public string EventName { get; set; }
        public string Profile { get; set; }
    
        public virtual ControlSpace ControlSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LightZone> LightZones { get; set; }
        public virtual EventDevice EventDevice { get; set; }
        public virtual Partition Partition { get; set; }
    }
}
