//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LightStrip : LightElement
    {
        public int StartPoint { get; set; }
        public int PointCount { get; set; }
        public Direction Direction { get; set; }
        public string ColorSequence { get; set; }
    }
}
