//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LSModelContainer : DbContext
    {
        public LSModelContainer()
            : base("name=LSModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ControlSpace> ControlSpaces { get; set; }
        public virtual DbSet<ControlChannel> ControlChannels { get; set; }
        public virtual DbSet<ControlDevice> ControlDevices { get; set; }
        public virtual DbSet<EventChannel> EventChannels { get; set; }
        public virtual DbSet<EventDevice> EventDevices { get; set; }
        public virtual DbSet<LightElement> LightElements { get; set; }
        public virtual DbSet<LightZone> LightZones { get; set; }
        public virtual DbSet<Gamma> Gammas { get; set; }
        public virtual DbSet<Partition> Partitions { get; set; }
        public virtual DbSet<BaseEffect> BaseEffects { get; set; }
        public virtual DbSet<Pattern> Patterns { get; set; }
        public virtual DbSet<Scene> Scenes { get; set; }
        public virtual DbSet<Effect> Effects { get; set; }
        public virtual DbSet<EnvironmentItem> EnvironmentItems { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<LE_Type> LE_Types { get; set; }
        public virtual DbSet<EffectPart> EffectParts { get; set; }
        public virtual DbSet<EffectPartType> EffectPartTypes { get; set; }
        public virtual DbSet<LE_Proxy> LE_Proxies { get; set; }
        public virtual DbSet<CustomGamma> CustomGammas { get; set; }
    }
}
